<?php

namespace ChatCreeSoftware\CoreBundle\Repository;

/**
 * ConfigDataRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ConfigDataRepository extends \Doctrine\ORM\EntityRepository
{
    public function findVatForDate( $date ) {
        $vatQuery = $em->createQuery( "select c from CoreBundle:ConfigData c where c.name='TVA' and c.date in (select MAX(d.date) from CoreBundle:ConfigData d where d.name='TVA' and d.date <= ?1)" );
        $vatQuery->setParameter(1,$date );
        $vatData =  $vatQuery->getResult();        
        $vat = floatval($vatData[0]->getValue());
        
        return $vat;
    }
}
