<?php

namespace ChatCreeSoftware\CoreBundle\Repository;

/**
 * ConfigDataRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ConfigDataRepository extends \Doctrine\ORM\EntityRepository
{
}
