ChatCreeSoftware\FileserverBundle\Entity\FileLink:
  type: entity
  table: FileLink
  id:
    id:
      type: integer
      generator:
         strategy: AUTO  
  fields:
    file:               { type: string(512) }
    token:              { type: string(512) }
    date:               { type: datetime }
  manyToOne:
    user:
      targetEntity: ChatCreeSoftware\CoreBundle\Entity\User
      inversedBy: filelinks
    project:
      targetEntity: ChatCreeSoftware\CoreBundle\Entity\Project
      inversedBy: filelinks
  lifecycleCallbacks: {  }
