ChatCreeSoftware\CoreBundle\Entity\Log:
  type: entity
  repositoryClass: ChatCreeSoftware\CoreBundle\Repository\LogRepository
  table: CoreLog
  id:
    id:
      type: integer
      generator:
         strategy: AUTO  
  fields:
    timestamp:   { type: datetime }
    action:      { type: string(255) }
    ip:          { type: string(64), nullable: true }
    detail:      { type: string(255), nullable: true }
  manyToOne:
    user:
      targetEntity: User
      inversedBy: logs
  lifecycleCallbacks: {  }
