ChatCreeSoftware\CoreBundle\Entity\Reset:
  type: entity
  table: CoreReset
  id:
    id:
      type: integer
      generator:
         strategy: AUTO  
  fields:
    timestamp:  { type: datetime }
    token:      { type: string(512) }
    mail:       { type: string(255) }
    ip:         { type: string(39) }
  manyToOne:
    user:
      targetEntity: User
      inversedBy: resets
  lifecycleCallbacks: {  }
